baseURL = 'https://SyedaEasha.github.io/ali-healthcare-solutions/'o
title = "Ali Healthcare Solutions"

[params]
  phone = "+1 (800) 000-0000"     
  email = "syedaeasha15@gmail.com" 
  whatsapp = "=923130546260"            
